- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "/vagrant/irix/Foundation/disc1"
    - "/vagrant/irix/Development/devfoundations"

- name: Fetch foundation disc 1
  get_url:
    url: "{{ foundation_baseurl }}{{ foundation_disc1 }}"
    dest: "/vagrant/irix/Foundation/disc1/{{ foundation_disc1 }}"  

- name: Fetch development foundations
  get_url:
    url: "{{ devel_baseurl }}/{{ devel_devfoundations }}"
    dest: "/vagrant/irix/Development/devfoundations/{{ devel_devfoundations }}"

- name: Extracting foundation disc 1
  unarchive:
    src: "/vagrant/irix//Foundation/disc1/{{ foundation_disc1 }}"
    dest: "/vagrant/irix//Foundation/disc1/"
    copy: no
    extra_opts:
    - --strip-components=1
    creates: "/vagrant/irix//Foundation/disc1/RELEASE.info"

- name: Extracting development foundations
  unarchive:
    src: "/vagrant/irix/Development/devfoundations/{{ devel_devfoundations }}"
    dest: "/vagrant/irix/Development/devfoundations/"
    copy: no
    extra_opts:
    - --strip-components=1
    creates: "/vagrant/irix/Development/devfoundations/CDrelnotes"
